namespace SpriteKind {
    export const levelOneAlien = SpriteKind.create()
    export const levelTwoAlien = SpriteKind.create()
}
function level_3 () {
    tiles.setTilemap(tilemap`level1`)
}
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile13`, function (sprite, location) {
    level_2()
})
function level_2 () {
    tiles.setTilemap(tilemap`level1`)
    alien_L2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.levelTwoAlien)
}
function level_1 () {
    tiles.setTilemap(tilemap`level1`)
    alien_L1 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.levelOneAlien)
}
sprites.onCreated(SpriteKind.levelOneAlien, function (sprite) {
    sprite.setVelocity(-90, 0)
    sprite.x = astronaut.x + 80
    sprite.y = randint(astronaut.y - 15, astronaut.y + 15)
})
sprites.onCreated(SpriteKind.levelTwoAlien, function (sprite) {
    sprite.setVelocity(-90, 0)
    sprite.x = astronaut.x + 80
    sprite.y = randint(astronaut.y - 15, astronaut.y + 15)
})
sprites.onCreated(SpriteKind.Player, function (sprite) {
    tiles.placeOnRandomTile(sprite, assets.tile`myTile12`)
})
let alien_L1: Sprite = null
let alien_L2: Sprite = null
let astronaut: Sprite = null
astronaut = sprites.create(img`
    .........fffffffff............
    ........ff1111111fff..........
    .......ff111111fffff..........
    ......ff111111ff999ff.........
    ......f111122ff99199ff........
    ......f22222ff9999199f........
    ......f88888f99999999f........
    ......f1111f999999999f........
    ......f1111f999999999f........
    ......f11111fff999999f........
    ......f1111111ffff99ff........
    ......ff111111111ffff.........
    .......f11fffff111f...........
    ......ff1ff111f11ff...........
    ......f11f1122f11f............
    ......f11f2228f11f............
    ......f11f8888f11f............
    ......f11f1111f11f............
    ......f11f1111f11f............
    ......f11f1111fffff...........
    ......f11f11111111f...........
    ......f11ff1111111f...........
    ......ff11fffffffff...........
    .......ff1111111f.............
    ........ff111111f.............
    .........f111111f.............
    .........f111111f.............
    .........f111111ff............
    .........f1111111f............
    .........fffffffff............
    `, SpriteKind.Player)
controller.moveSprite(astronaut, 100, 100)
scene.cameraFollowSprite(astronaut)
level_1()
forever(function () {
    astronaut.ay = 150
})
forever(function () {
    pause(500)
    alien_L1 = sprites.create(img`
        ..............aaa.............
        .............aaaaa............
        ............aaaaaaa...........
        ............aaaaaaaa..........
        ...........aaaaaaaaa..........
        ..........faaaaafaaa..........
        ..........ffaaaffaaa..........
        .........affaafffaaa..........
        .........aaaaaaaaaaa..........
        .........aaaaaaaaaa...........
        ..........fffffffaa...........
        ..........affffffaa...........
        ...........aaaaffaa...........
        .............aaaa.............
        ..............aa..............
        ..............aa..............
        ............aaaa..............
        ...2121aaaaaaaaa..............
        ....a21aaaa...aa..............
        ....aaaa......aa..............
        ..............aa..............
        ..............aa..............
        .............aaaa.............
        ............aaaaa.............
        ............aa.aa.............
        ...........aa..aa.............
        .........aaaa.aaa.............
        ........aaaa..aaa.............
        ........aa.....aa.............
        ...............a..............
        `, SpriteKind.levelOneAlien)
})
forever(function () {
    pause(500)
    alien_L2 = sprites.create(img`
        ..............999.............
        .............99999............
        ............9999999...........
        ............99999999..........
        ...........999999999..........
        ..........f99999f999..........
        ..........ff999ff999..........
        .........9ff99fff999..........
        .........99999999999..........
        .........9999999999...........
        ..........fffffff99...........
        ..........9ffffff99...........
        ...........9999ff99...........
        .............9999.............
        ..............99..............
        ..............99..............
        ............9999..............
        ...2121999999999..............
        ....9219999...99..............
        ....9999......99..............
        ..............99..............
        ..............99..............
        .............9999.............
        ............99999.............
        ............99.99.............
        ...........99..99.............
        .........9999.999.............
        ........9999..999.............
        ........99.....99.............
        ...............9..............
        `, SpriteKind.levelOneAlien)
})
