namespace SpriteKind {
    export const levelOneAlien = SpriteKind.create()
}
function level_3 () {
    tiles.setTilemap(tilemap`level1`)
}
function level_2 () {
    tiles.setTilemap(tilemap`level1`)
}
function level_1 () {
    tiles.setTilemap(tilemap`level1`)
    mySprite = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.levelOneAlien)
}
sprites.onCreated(SpriteKind.levelOneAlien, function (sprite) {
    sprite.setVelocity(-90, 0)
})
let alien_L1: Sprite = null
let mySprite: Sprite = null
let astronaut = sprites.create(img`
    .........fffffffff............
    ........ff1111111fff..........
    .......ff111111fffff..........
    ......ff111111ff999ff.........
    ......f111122ff99199ff........
    ......f22222ff9999199f........
    ......f88888f99999999f........
    ......f1111f999999999f........
    ......f1111f999999999f........
    ......f11111fff999999f........
    ......f1111111ffff99ff........
    ......ff111111111ffff.........
    .......f11fffff111f...........
    ......ff1ff111f11ff...........
    ......f11f1122f11f............
    ......f11f2228f11f............
    ......f11f8888f11f............
    ......f11f1111f11f............
    ......f11f1111f11f............
    ......f11f1111fffff...........
    ......f11f11111111f...........
    ......f11ff1111111f...........
    ......ff11fffffffff...........
    .......ff1111111f.............
    ........ff111111f.............
    .........f111111f.............
    .........f111111f.............
    .........f111111ff............
    .........f1111111f............
    .........fffffffff............
    `, SpriteKind.Player)
controller.moveSprite(astronaut, 100, 100)
scene.cameraFollowSprite(astronaut)
level_1()
forever(function () {
    astronaut.ay = 200
})
forever(function () {
    pause(4000)
    alien_L1 = sprites.create(img`
        ..............aaa.............
        .............aaaaa............
        ............aaaaaaa...........
        ............aaaaaaaa..........
        ...........aaaaaaaaa..........
        ..........faaaaafaaa..........
        ..........ffaaaffaaa..........
        .........affaafffaaa..........
        .........aaaaaaaaaaa..........
        .........aaaaaaaaaa...........
        ..........fffffffaa...........
        ..........affffffaa...........
        ...........aaaaffaa...........
        .............aaaa.............
        ..............aa..............
        ..............aa..............
        ............aaaa..............
        ...2121aaaaaaaaa..............
        ....a21aaaa...aa..............
        ....aaaa......aa..............
        ..............aa..............
        ..............aa..............
        .............aaaa.............
        ............aaaaa.............
        ............aa.aa.............
        ...........aa..aa.............
        .........aaaa.aaa.............
        ........aaaa..aaa.............
        ........aa.....aa.............
        ...............a..............
        `, SpriteKind.levelOneAlien)
    tiles.placeOnRandomTile(alien_L1, assets.tile`myTile10`)
})
